version: '3.8'

services:
  test:
    build:
      context: .
      target: test-stage
    environment:
      NODE_ENV: test
    command: ["npm", "run", "test"]
    volumes:
      - .:/app
      - /app/node_modules

  app:
    build:
      context: .
      target: production
    depends_on:
      - test
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      PORT: 8000
    env_file:
      - .env
    command: ["node", "dist/server.js"]
